### PR TITLE
Update BUILD.md

### PR DESCRIPTION
**Pull request by murillodigital**

### CODE REVIEW

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
This is a test

**Comment by hifi-gustavo** [comment]
<br/><br/>windows installer completed building and available for download at: http://cachefly.highfidelity.com//HighFidelity-Installer.dmg

**Comment by hifi-gustavo** [comment]
windows installer completed building and is available for download at: http://cachefly.highfidelity.com/HighFidelity-Beta-PR1-6e459e0.exe

**Comment by marko8904** [comment]
test this please and be nice

**Comment by hifi-gustavo** [comment]
$label installer completed building and is available for download at: http://deployment.highfidelity.com/jobs/pr-build/label%3D$label/26/HighFidelity-Beta-PR1-6e459e0.dmg

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
test

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
${ENV,var="label"} will be available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3D${ENV,var="label"}/28/HighFidelity-Beta-PR1-${GITHUB_COMMIT:0:7}.exe

**Comment by hifi-gustavo** [comment]
${ENV,var="label"} will be available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3D${ENV,var="label"}/28/HighFidelity-Beta-PR1-${GITHUB_COMMIT:0:7}.exe

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build will be available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/29/HighFidelity-Beta-PR1-6e459e09dc0fa4ef33d776da1fb458101d54d5b7.exe

**Comment by hifi-gustavo** [comment]
OS X build will be available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/29/HighFidelity-Beta-PR1-6e459e09dc0fa4ef33d776da1fb458101d54d5b7.dmg

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X installer completed building and is available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/30/HighFidelity-Beta-PR1-6e459e09dc0fa4ef33d776da1fb458101d54d5b7.dmg

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Mac OS X installer completed building and is available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/31/HighFidelity-Beta-PR1-6e459e09dc0fa4ef33d776da1fb458101d54d5b7.dmg

**Comment by marko8904** [comment]
test this please

**Comment by hifi-gustavo** [comment]
Windows build is available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dwindows/33/HighFidelity-Beta-PR1-6e459e09dc0fa4ef33d776da1fb458101d54d5b7.exe

**Comment by hifi-gustavo** [comment]
Mac OS X installer completed building and is available for download at: https://deployment.highfidelity.com/jobs/pr-build/label%3Dmacos/33/HighFidelity-Beta-PR1-6e459e09dc0fa4ef33d776da1fb458101d54d5b7.dmg

**Pull request closed without merging**
